import { RegularExpression, Wildcard } from 'objectmaphelper.js';

export var reactAppBrowserTab = {"title": "React App", "type": "BrowserTab"};
export var reactAppLoginA = {"container": reactAppBrowserTab, "id": new Wildcard("navLink"), "name": new Wildcard("Login"), "simplifiedInnerText": "Login", "tagName": "A", "visible": true};
export var reactAppPasswordText = {"container": reactAppBrowserTab, "name": new Wildcard("password"), "tagName": "INPUT", "type": "text", "visible": true};
export var reactAppUsernamePassword = {"container": reactAppBrowserTab, "name": "password", "tagName": "INPUT", "type": "password", "visible": true};
export var reactAppLoginButton = {"container": reactAppBrowserTab, "name": "Login", "simplifiedInnerText": "Login", "tagName": "BUTTON", "type": new Wildcard("button"), "visible": true};
export var reactAppAddMovieA = {"container": reactAppBrowserTab, "simplifiedInnerText": "add movie", "tagName": "A", "visible": true};
export var reactAppTitleText = {"container": reactAppBrowserTab, "name": "title", "tagName": "INPUT", "type": "text", "visible": true};
export var reactAppCategoriesSelectMultiple = {"container": reactAppBrowserTab, "name": "categories", "tagName": "SELECT", "type": "select-multiple", "visible": true};
export var reactAppDirectorText = {"container": reactAppBrowserTab, "name": "director", "tagName": "INPUT", "type": "text", "visible": true};
export var reactAppDescriptionTEXTAREA = {"container": reactAppBrowserTab, "name": "description", "tagName": "TEXTAREA", "visible": true};
export var reactAppFileText = {"container": reactAppBrowserTab, "name": "file", "tagName": "INPUT", "type": "text", "visible": true};
export var titleReactAppTypeBrowserTabDOCUMENTHTML1BODY1DIV1DIV1DIV1DIV6DIV1Svg5Path1 = "{title='React App' type='BrowserTab'}.DOCUMENT.HTML1.BODY1.DIV1.DIV1.DIV1.DIV6.DIV1.svg5.path1";
export var reactAppSaveMovieButton = {"container": reactAppBrowserTab, "simplifiedInnerText": "Save Movie", "tagName": "BUTTON", "type": "button", "visible": true};
export var titleReactAppTypeBrowserTabDOCUMENTHTML1BODY1DIV1DIV1DIV1DIV6DIV1Svg4Path1 = "{title='React App' type='BrowserTab'}.DOCUMENT.HTML1.BODY1.DIV1.DIV1.DIV1.DIV6.DIV1.svg4.path1";
export var reactAppProfileA = {"container": reactAppBrowserTab, "id": "navLink", "simplifiedInnerText": "Profile", "tagName": "A", "visible": true};
export var reactAppSearchSearch = {"container": reactAppBrowserTab, "name": "search", "tagName": "INPUT", "type": "search", "visible": true};
export var reactAppLooksGoodDIV = {"container": reactAppBrowserTab, "simplifiedInnerText": "Looks good!", "tagName": "DIV", "visible": true};
export var containerTitleReactAppTypeBrowserTabSimplifiedInnerTextLooksGoodTagNameDIVVisibleTrueSvg5 = "{container={title='React App' type='BrowserTab'} simplifiedInnerText='Looks good!' tagName='DIV' visible='true'}.svg5";
export var containerTitleReactAppTypeBrowserTabSimplifiedInnerTextLooksGoodTagNameDIVVisibleTrueSvg1 = "{container={title='React App' type='BrowserTab'} simplifiedInnerText='Looks good!' tagName='DIV' visible='true'}.svg1";
export var containerTitleReactAppTypeBrowserTabSimplifiedInnerTextLooksGoodTagNameDIVVisibleTrueSvg2 = "{container={title='React App' type='BrowserTab'} simplifiedInnerText='Looks good!' tagName='DIV' visible='true'}.svg2";
export var containerTitleReactAppTypeBrowserTabSimplifiedInnerTextLooksGoodTagNameDIVVisibleTrueSvg3 = "{container={title='React App' type='BrowserTab'} simplifiedInnerText='Looks good!' tagName='DIV' visible='true'}.svg3";
export var titleReactAppTypeBrowserTabDOCUMENTHTML1BODY1DIV1DIV1DIV1DIV6DIV1Svg2Path1 = "{title='React App' type='BrowserTab'}.DOCUMENT.HTML1.BODY1.DIV1.DIV1.DIV1.DIV6.DIV1.svg2.path1";
export var reactAppButton = {"container": reactAppBrowserTab, "simplifiedInnerText": "#", "tagName": "BUTTON", "type": "button", "visible": true};
export var reactAppLoginA_2 = {"container": reactAppBrowserTab, "name": new Wildcard("Cancel"), "simplifiedInnerText": "Login", "tagName": "A", "visible": true};
export var reactAppUsernameText = {"container": reactAppBrowserTab, "name": "username", "tagName": "INPUT", "type": "text", "visible": true};
export var reactAppPasswordPassword = {"container": reactAppBrowserTab, "name": "password", "tagName": "INPUT", "type": "password", "visible": true};
export var reactAppLoginA_3 = {"container": reactAppBrowserTab, "name": "Cancel", "simplifiedInnerText": "Login", "tagName": "A", "visible": true};
export var reactAppLoginButton_2 = {"container": reactAppBrowserTab, "name": "Login", "simplifiedInnerText": "Login", "tagName": "BUTTON", "type": "button", "visible": true};
export var reactAppAutothonChallengeByDIV = {"container": reactAppBrowserTab, "occurrence": 2, "simplifiedInnerText": "Autothon challenge by", "tagName": "DIV", "visible": true};
export var reactAppBrowserTab_2 = {"occurrence": 2, "title": "React App", "type": "BrowserTab"};
export var reactAppButton_2 = {"container": reactAppBrowserTab_2, "simplifiedInnerText": "#", "tagName": "BUTTON", "type": "button", "visible": true};
export var reactAppLoginA_4 = {"container": reactAppBrowserTab_2, "name": "Cancel", "simplifiedInnerText": "Login", "tagName": "A", "visible": true};
export var reactAppUsernameText_2 = {"container": reactAppBrowserTab_2, "name": "username", "tagName": "INPUT", "type": "text", "visible": true};
export var reactAppPasswordPassword_2 = {"container": reactAppBrowserTab_2, "name": "password", "tagName": "INPUT", "type": "password", "visible": true};
export var reactAppLoginButton_3 = {"container": reactAppBrowserTab_2, "name": "Login", "simplifiedInnerText": "Login", "tagName": "BUTTON", "type": "button", "visible": true};
export var reactAppMoviesA = {"container": reactAppBrowserTab, "simplifiedInnerText": "Movies", "tagName": "A", "visible": true};
export var reactAppTomAndJerrryByTimStoryRatingStatusAvailableViewMoreEditDIV = {"container": reactAppBrowserTab, "simplifiedInnerText": "Tom and Jerrry by Tim Story Rating: Status: Available View more Edit", "tagName": "DIV", "visible": true};
export var reactAppEditButton = {"container": reactAppBrowserTab, "simplifiedInnerText": "Edit", "tagName": "BUTTON", "type": "button", "visible": true};
